export const companions = {
  eyebrow: "LES AMIS DU VOYAGE",
  title: "Mes compagnons",
  intro:
    "Chaque rencontre garde un peu de la magie du chemin. Retrouve tes amis, découvre leur histoire et choisis leur petit nom.",
  family: (n: number) => `Les compagnons du monde ${n}`,
  count: (n: number) => `${n} compagnon${n > 1 ? "s" : ""} rencontré${n > 1 ? "s" : ""}`,
  empty: "Ton premier compagnon t’attend. Au bout du chemin, le gardien viendra te rejoindre.",
  unknown: "Une rencontre à venir",
  unknownGuardian: "Un gardien à rencontrer",
  eggHint: "À découvrir dans un œuf",
  guardianHint: "Au bout du chemin de ce monde",
  story: "Son histoire",
  home: "Un ami pour la suite du voyage",
  savedName: "Son petit nom est enregistré.",
  meetTitle: "Une rencontre légendaire.",
  meetKicker: "LE GARDIEN DU MONDE",
  added: "Ton nouvel ami a rejoint tes compagnons.",
  reunited: "Ton compagnon est heureux de te retrouver.",
  visit: "Retrouver mon compagnon",
  nextWorld: "Un nouveau monde s’ouvre à nous.",
  unknownGlyph: "✧",
  back: "←",
};
