export const daily = {
  eyebrow: "Le rendez-vous avec Teddy",
  welcome: "Le chemin t’attend.",
  invitation: "Un petit moment ensemble, une nouvelle découverte à chaque pas.",
  first: "Notre première aventure",
  firstHint:
    "Prépare ton portrait avec un parent. Ensuite, je t’accompagne pour découvrir ton chemin.",
  hello: (name: string) => `Rebonjour, ${name} !`,
  resume: "Reprendre mon aventure",
  resumeHint: "Ta place est gardée. Nous repartons ensemble là où tu t’es arrêté.",
  other: "Ou choisir un autre aventurier",
  keyboard: "Tu peux aussi taper les chiffres au clavier.",
  forgottenChild: "Code oublié ? Un parent peut le changer dans son espace.",
  addProfile: "Ajouter un enfant depuis l’espace parent",
  setupStep: (n: number) => `Préparatifs · ${n} sur 4`,
  confirmChild: "Retape ton code secret",
  confirmParent: "Confirmez le code parent",
  confirmHint: "Encore une fois pour être sûr de le retrouver.",
  mismatch: "Les deux codes sont différents. On reprend tranquillement.",
  recoveryChecked: "J’ai conservé ce code dans un endroit sûr.",
  configured: "Le foyer est déjà prêt. Retrouve ton profil à l’accueil.",
  readyHint:
    "Choisis ton portrait et tape ton code. Teddy préparera ton premier chemin avec quelques calculs, sans note.",
  saving: "Je garde ta place…",
  stop: "M’arrêter pour aujourd’hui",
  restTitle: "On se retrouve bientôt.",
  restHint: "Ta place est gardée. Tu pourras retrouver ton calcul et tes compagnons à ton retour.",
  restSaved: "Ton aventure est enregistrée.",
  suggestedTitle: "Une petite pause ensemble ?",
  suggestedHint:
    "Nous avons déjà fait un bout de chemin. Tu peux te reposer, ou continuer si tu en as envie.",
  limitTitle: "Le chemin se repose jusqu’à demain.",
  limitHint:
    "Le temps de jeu prévu avec ton parent est terminé pour aujourd’hui. Tes compagnons t’attendront ici.",
  continue: "Continuer mon chemin",
  home: "Retour à l’accueil",
  collection: "Retrouver mes compagnons",
  readyForTomorrow: "À bientôt, Teddy",
  pauseSaving: "Attends que ta place soit enregistrée avant de fermer.",
  diagnosticEyebrow: "Notre premier voyage",
  diagnosticTitle: "Préparons ton chemin",
  diagnosticIntro:
    "Quelques petits calculs pour choisir les bons pas pour toi. Prends ton temps : je suis là pour t’aider.",
  diagnosticBegin: "Préparer mon chemin",
  diagnosticDone: "Ton chemin est prêt !",
  diagnosticDoneHint: "Nous allons avancer à ton rythme. Les premières découvertes t’attendent.",
  diagnosticMap: "Découvrir ma carte",
  recalibrationEyebrow: "Un nouveau point de départ",
  recalibrationHint:
    "Quelques calculs pour ajuster la suite à ton rythme. Tu gardes tout ce que tu as déjà découvert.",
  diagnosticProgress: (n: number, total: number) => `${n} repères sur ${total}`,
} as const;
