export const eggShop = {
  eyebrow: "Une halte avec Teddy",
  title: "La clairière aux œufs",
  intro: "Tes aventures font grandir ta collection. Un petit compagnon se cache peut-être ici…",
  eggName: "L’œuf des sous-bois",
  eggDescription:
    "Une surprise parmi les compagnons communs et rares des mondes que tu as ouverts.",
  price: (n: number) => `${n} pièces`,
  coins: "Tes pièces",
  shards: "Tes éclats",
  buy: (n: number) => `Choisir cet œuf · ${n} pièces`,
  after: (n: number) => `Après cet achat : ${n} pièces.`,
  missing: (n: number) =>
    `Encore ${n} pièces pour cet œuf. Tu en trouveras en poursuivant ton chemin.`,
  continue: "Poursuivre mon aventure",
  collection: "Mes compagnons",
  back: "← Retour au chemin",
  rules: "Les pièces se gagnent en jouant. Tu peux aussi les garder pour plus tard.",
  duplicateHint:
    "Un compagnon déjà rencontré t’offre des éclats. Après plusieurs retrouvailles, un nouveau compagnon est garanti s’il en reste à découvrir.",
  guardianHint: "Les légendaires t’attendent auprès des gardiens.",
  unavailable: "Les œufs se préparent encore. Ton aventure peut continuer.",
  loading: "Teddy prépare la clairière…",
  buying: "Teddy prend soin de ton œuf…",
  waiting: "Ton œuf est prêt !",
  paid: (n: number) =>
    `Ton achat est enregistré. Solde après cet achat : ${n} pièce${n > 1 ? "s" : ""}.`,
  open: "Ouvrir mon œuf",
  openHint: "Prends ton temps. Ton compagnon t’attend.",
  newFriend: "Un nouveau compagnon !",
  reunion: "De jolies retrouvailles !",
  named: (name: string) => `Voici ${name}`,
  newHint: "Il a rejoint ta collection. Allons faire connaissance !",
  duplicate: (name: string, n: number) =>
    `${name} est déjà ton compagnon. Ces retrouvailles t’offrent ${n} éclats !`,
  shardsGain: (n: number) => `+${n} éclats`,
  pity: "Un nouveau compagnon t’attendait après tes retrouvailles.",
  visit: "Retrouver mon compagnon",
  returnShop: "Revenir à la clairière",
  saved: "Ton compagnon et tes gains sont enregistrés.",
  retry: "Réessayer",
  network: "La connexion a été interrompue. Réessaie pour retrouver ton œuf ou ta rencontre.",
  storage:
    "Ce navigateur ne peut pas garder ton achat en attente. Autorise le stockage, puis réessaie.",
  auth: "Retrouve ton profil pour continuer cette rencontre.",
  login: "Retrouver mon profil",
  broke: "Tes pièces ont changé. Tu peux poursuivre ton chemin et revenir plus tard.",
  error: "La clairière n’est pas encore prête. Réessaie dans un instant.",
} as const;
