export const evolution = {
  title: "Un peu plus grand, toujours ton ami",
  kicker: "Un compagnon qui grandit",
  entry: "Faire grandir mon compagnon",
  preview: "Découvrir son prochain stade",
  stage: { 1: "Bébé", 2: "Ado", 3: "Adulte" } as Record<number, string>,
  current: "Aujourd’hui",
  next: "Après avoir grandi",
  before: "Avant",
  now: "Le voici maintenant",
  grown: (name: string) => `${name} a grandi !`,
  description: "Son allure change. Il garde son nom, son histoire et sa place à tes côtés.",
  cosmetic: "Grandir change seulement son apparence. Les calculs et l’aventure restent les mêmes.",
  balance: (amount: number) => `Tu as ${amount} éclats`,
  cost: (amount: number) => `Pour grandir : ${amount} éclats`,
  after: (amount: number) => `Il te restera ${amount} éclats`,
  confirm: (amount: number) => `Faire grandir · ${amount} éclats`,
  missing: (amount: number) => `Encore ${amount} éclats pour grandir.`,
  earn: "Quand tu retrouves un compagnon dans un œuf, tu reçois des éclats. Tu peux continuer ton aventure à ton rythme.",
  back: "Retour à sa fiche",
  keep: "Garder ce stade pour le moment",
  return: (name: string) => `Retrouver ${name}`,
  historical: (amount: number) => `Après cette évolution : ${amount} éclats`,
  spent: (amount: number) => `${amount} éclats ont accompagné ce changement.`,
  complete: "Ton compagnon a atteint son stade adulte.",
  unavailable: "Ton compagnon reste à tes côtés. Son prochain stade n’est pas encore disponible.",
  loading: "Je retrouve ton compagnon…",
  saving: "Je garde ce moment…",
  retry: "Réessayer",
  imageLoading: "Son portrait arrive…",
  imageError: "Son portrait n’a pas pu s’afficher. Retrouvons-le avant de le faire grandir.",
  errors: {
    NETWORK:
      "La connexion s’est interrompue. Je retrouverai ce changement sans dépenser deux fois.",
    STORAGE:
      "Je n’arrive pas à garder ta demande sur cet appareil. Aucun nouveau changement n’est lancé.",
    UNAUTHENTICATED: "Retrouve ton profil pour continuer avec ton compagnon.",
    BROKE: "Tes éclats ont changé. Tu peux continuer l’aventure et revenir plus tard.",
    CHANGED:
      "Ton compagnon ou son prochain stade a changé. Regarde ce nouvel aperçu avant de choisir.",
    UNAVAILABLE:
      "Ce changement n’est pas disponible pour le moment. Ton compagnon est toujours dans ta collection.",
    INVALID: "Je n’ai pas reconnu cette demande. Retrouvons ton compagnon.",
  } as Record<string, string>,
};
