export const forest = {
  title: "Le passage des lucioles",
  eyebrow: "LÀ OÙ LES ARBRES MURMURENT",
  welcome: "Un petit pas, une nouvelle lumière.",
  invitation:
    "Le sentier dort encore. Viens, on va le réveiller ensemble, jusqu’au passage dans les racines.",
  begin: "Allons-y",
  loading: "Teddy retrouve ton chemin…",
  sceneLoading: "La forêt s’éveille…",
  sceneFallback: "La forêt se repose. Tu peux continuer à jouer avec Teddy.",
  help: "Un coup de patte",
  helpIntro: "Prenons le temps de regarder ensemble.",
  explore: "Éclairer la suite",
  reveal: "Voir le résultat",
  retry: "Je réessaie",
  helpLabels: {
    comp10: "Combien de places restent libres dans les dix cases ?",
    add: "Pars du premier nombre, puis avance sur la ligne.",
    sub: "Pars du premier nombre, puis recule sur la ligne.",
    mult: "Regarde les groupes : il y a autant de lumières dans chacun.",
  },
  answerLabel: "Ta réponse",
  submit: "Valider",
  backspace: "Effacer un chiffre",
  clear: "Tout effacer",
  question: "À TOI DE JOUER",
  again: "ESSAYONS ENSEMBLE",
  correct: "Une lumière de plus !",
  accompanied: "On avance ensemble !",
  feedback: "Regarde, notre sentier s’éclaire. Teddy peut continuer son voyage.",
  next: "Continuer le chemin",
  finale: "Le passage s’est éveillé.",
  encounter:
    "Voici Lumo, le petit habitant des racines. Il vient admirer toutes les lumières que nous avons allumées.",
  results: "Notre souvenir",
  resultTitle: "Un beau bout de chemin",
  earned: "pièces gagnées",
  balance: "dans ta poche",
  saved: "Ton aventure est enregistrée.",
  alreadyEarned: "Les pièces de ce passage sont déjà dans ta poche.",
  returnMap: "Retrouver mon chemin",
  mapTitle: "La forêt des premiers pas",
  mapEyebrow: "TON AVENTURE AVEC TEDDY",
  mapIntro: "Des lueurs entre les arbres, un ami derrière les racines. Le chemin t’attend.",
  continue: "Continuer l’aventure",
  resume: "Reprendre mon passage",
  resumeResult: "Retrouver mon souvenir",
  mapPath: "Les étapes de ton chemin",
  current: "Tu es ici",
  completed: "Passage ouvert",
  locked: "À découvrir",
  guardianStep: "Gardien",
  guardian: "Le gardien de la forêt",
  guardianHint: "Au bout du chemin, une rencontre légendaire t’attend.",
  guardianIntro: "Le gardien nous attend. Éclairons les dernières lueurs de ce monde ensemble.",
  legendary: "Un nouvel ami dans ta collection",
  collection: "Mes compagnons",
  shop: "La cabane aux œufs",
  pause: "Pause",
  pauseTitle: "On souffle un peu ?",
  pauseHint: "Teddy garde ta place. Tu retrouveras ce passage quand tu reviendras.",
  resumePlay: "Je reprends",
  reduced: "Moins de mouvement",
  soundOn: "Son activé",
  soundOff: "Son coupé",
  pending: "Ta réponse est gardée. On reprend dès que le réseau revient.",
  sending: "Teddy garde ta place…",
  retryNetwork: "Réessayer l’envoi",
  loadError: "Le chemin attend le réseau. Réessayons dans un instant.",
  storageError:
    "La sauvegarde de ce navigateur est indisponible. Garde cette page ouverte jusqu’à la confirmation de Teddy.",
  authError: "Retrouve ton profil pour reprendre le chemin.",
  login: "Retrouver mon profil",
  refresh: "Retrouver ma place",
  sessionChanged: "Le chemin a avancé sur un autre écran. Retrouvons ta place.",
  lights: (n: number, total: number) => `${n} / ${total} lueurs`,
  step: (n: number) => `Étape ${n}`,
  world: (n: number) => `MONDE ${n}`,
  stars: (n: number) => `${n} étoile${n > 1 ? "s" : ""}`,
  greeted: (name: string) => `Le chemin de ${name}`,
  keys: "1–4 pour choisir · Entrée pour valider · Échap pour souffler",
  teddy: "TEDDY",
  arrow: "→",
  star: "★",
  emptyStar: "☆",
  check: "✓",
  guardianSymbol: "✧",
  light: "✦",
};
