/** Adult copy for the TEDDy family notebook. */
export const parent = {
  keyboard: "Vous pouvez aussi saisir les chiffres au clavier.",
  required:
    "Cet espace est réservé aux parents. Saisissez le code parent pour ouvrir le carnet ; le code enfant ne donne pas accès aux réglages.",
  nudgeHint: "Une invitation douce en fin de niveau, une fois par jour. L’enfant peut continuer.",
  unreachableTime: (max: number) =>
    `Cette valeur enregistrée dépasse le plafond de l’estimation (${max} min) : elle ne peut pas déclencher la pause ou la limite. Choisissez une durée plus courte pour l’activer.`,
  lockHint:
    "Le niveau en cours reste accessible. Au seuil atteint, aucune nouvelle partie ne démarre avant le lendemain, dans le fuseau indiqué.",
  brand: "TEDDy",
  notebook: "Le carnet de famille",
  nav: "Espace parent",
  skip: "Aller au contenu",
  dashboard: "Suivi",
  settings: "Réglages",
  profiles: "Profils",
  worlds: "Mondes",
  access: "Accès & secours",
  title: (name: string) => `Le voyage de ${name}`,
  intro: "Quelques repères pour accompagner, à son rythme.",
  profile: "Profil suivi",
  apply: "Afficher",
  period: "Période des réponses",
  recent: (n: number) => `${n} derniers jours`,
  all: "Depuis le début",
  periodHint:
    "Fenêtre glissante, à l’heure indiquée. Les premières réponses comptent, même après une aide ; les réessais et le diagnostic sont exclus.",
  range: (start: string, end: string) => `Du ${start} (exclu) au ${end} (inclus)`,
  asOf: (date: string) => `État au ${date}`,
  noAnswers: "Aucune première réponse sur cette période.",
  noHistory:
    "Le voyage commence. Le diagnostic prépare le parcours ; les repères de justesse apparaîtront après les premiers calculs de niveau.",
  accuracy: "Réponses justes",
  speed: "Temps de réponse moyen",
  empty: "Pas de données",
  answers: (correct: number, total: number) => `${correct} sur ${total} premières réponses`,
  sample: (n: number) => `${n} première${n > 1 ? "s" : ""} réponse${n > 1 ? "s" : ""}`,
  small:
    "Petit échantillon : ces valeurs décrivent seulement les réponses observées. Aucune tendance n’est conclue.",
  noComparison: "Comparaison indisponible : une des deux périodes n’a aucune réponse.",
  prior: (n: number) => `Comparaison aux ${n} jours précédents`,
  comparison: (current: number, previous: number) =>
    `${current} réponses sur la période · ${previous} sur la précédente`,
  stable: "Écart limité dans les seuils du suivi.",
  delta: (n: string) => `${n} points de justesse sur les réponses observées.`,
  speedHint:
    "Moyenne des premières réponses, justes ou non. La fluence se construit avec des réponses à la fois justes et suffisamment rapides ; cette moyenne seule ne mesure pas la maîtrise.",
  seconds: (n: string) => `${n} s`,
  skills: "Les compétences, pas à pas",
  skillsHint:
    "Justesse et temps : période choisie. Maîtrise : état actuel sur tous les calculs du socle, y compris ceux encore à découvrir.",
  mastered: (n: number, total: number) => `${n} / ${total} calculs maîtrisés`,
  unseen: "Pas encore exploré",
  seen: (n: number) => `${n} calcul${n > 1 ? "s" : ""} rencontré${n > 1 ? "s" : ""}`,
  daily: "Au fil des jours",
  dailyHint:
    "Justesse quotidienne sur la période. Un tiret indique un jour sans première réponse ; 0 % signifie que les réponses observées n’étaient pas encore justes.",
  noDay: "—",
  date: "Jour",
  count: "Réponses",
  right: "Justesse",
  review: "À accompagner",
  reviewHint:
    "État actuel du socle. Ces groupes peuvent se recouper. Le jeu choisit les révisions ; aucune liste n’est à terminer aujourd’hui.",
  weak: "À consolider",
  due: "À revoir maintenant",
  slow: "À automatiser",
  reviewEmpty: "Aucun calcul avec erreur ou lenteur dans la sélection à accompagner.",
  reviewUnseen: "Les calculs à accompagner apparaîtront après les premières rencontres.",
  reason: {
    wrong: "À reprendre ensemble",
    slow: "Encore à automatiser",
    "wrong-and-slow": "À reprendre et automatiser",
  },
  today: "Aujourd’hui",
  noToday: "Aucune réponse de niveau enregistrée aujourd’hui.",
  minutes: (n: number) => `${n} min estimée${n > 1 ? "s" : ""}`,
  zeroMinutes: "Moins d’une minute estimée",
  timeHint: (cap: number, zone: string) =>
    `Estimation entre la première et la dernière réponse du jour, réessais inclus, plafonnée à ${cap} min. Les interruptions entre ces réponses peuvent être incluses. Une seule réponse donne 0 min ; ce n’est pas un chronomètre actif. Diagnostic exclu. Journées : ${zone}.`,
  regularity: "Un rythme qui lui ressemble",
  days: (n: number) => `${n} jour${n > 1 ? "s" : ""} avec des réponses depuis le début`,
  streak: (n: number) => `${n} jour${n > 1 ? "s" : ""} consécutif${n > 1 ? "s" : ""} actuellement`,
  rest: "Les pauses font partie du voyage. Aucune série à préserver à tout prix.",
  adventure: "Son aventure",
  world: (n: number) => `Monde ${n}`,
  levels: (n: number, total: number) => `${n} / ${total} étapes terminées`,
  creatures: (n: number) => `${n} compagnon${n > 1 ? "s" : ""} différent${n > 1 ? "s" : ""}`,
  adventureEmpty: "L’aventure n’est pas disponible pour le moment.",
  pending: (n: number) => `${n} monde${n > 1 ? "s" : ""} à regarder`,
  household: "Pour toute la famille",
  saved: "Réglage enregistré.",
  saving: "Enregistrement…",
  saveFailure:
    "Enregistrement non confirmé. La dernière valeur confirmée est affichée ; vous pouvez réessayer.",
  motion: "Mouvements réduits",
  motionHint:
    "Sur cet appareil : conserve le choix déjà utilisé dans l’aventure. La préférence de votre système reste prioritaire.",
  motionUnavailable: "Ce navigateur ne peut pas conserver ce choix.",
  recalibrate: (name: string) => `Recalibrer le parcours de ${name}`,
  recalibrateHint:
    "Un nouveau diagnostic sera proposé après la partie en cours. Les acquis, les compagnons et la progression sont conservés ; le recalibrage ne peut pas faire reculer la maîtrise.",
  recalibrateDone: "Recalibrage demandé. La partie en cours reste prioritaire.",
  accessTitle: "Garder les clés du voyage",
  accessIntro: "Le code parent protège les réglages et tous les profils de ce foyer.",
  accessChild: "Code enfant oublié",
  accessChildHint:
    "Choisissez le profil pour définir et confirmer un nouveau code enfant. Sa progression et sa partie en cours restent en place.",
  accessParent: "Code parent & récupération",
  accessParentHint:
    "Le code de secours conservé lors de l’installation permet de définir un nouveau code parent. Il est remplacé après utilisation : conservez alors le nouveau.",
  recover: "Récupérer ou changer le code parent",
  accessExit: "Quittez l’espace parent avant de rendre l’appareil à l’enfant.",
  create: "Ajouter un profil",
  name: "Prénom",
  avatar: "Portrait",
  childPin: "Code enfant",
  confirmPin: "Confirmer le code enfant",
  mismatch: "Les deux codes doivent être identiques.",
  next: "Continuer",
  cancel: "Annuler",
  createDone: "Profil créé. Son premier voyage l’attend à l’accueil.",
  addHint:
    "Chaque enfant garde son parcours, ses compagnons et son code. Le code parent reste commun au foyer.",
  savePin: "Enregistrer ce code",
  confirmParentPin: "Confirmer le code parent",
  savedRecovery: "J’ai conservé mon nouveau code de secours",
  backHome: "Retour à l’accueil",
  preview: "Aperçu du contenu proposé",
  background: "Décor",
  tiles: "Éléments du chemin",
  teddy: "Teddy dans ce monde",
  previewUnavailable: "Aperçu indisponible",
  characters: "Compagnons de ce monde",
  creatureStages: ["Bébé", "Adolescent", "Adulte"],
  noCharacters: "Aucun compagnon disponible dans cet aperçu.",
  approveTitle: "Rendre ce monde accessible ?",
  approveHint:
    "Après confirmation, ce monde rejoindra le parcours familial lorsque la progression le permettra.",
  approveConfirm: "Confirmer l’approbation",
  previewHint:
    "Regardez le décor et les compagnons avant de décider. Votre décision concerne le contenu proposé à toute la famille.",
} as const;
